//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Web.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalle
    {
        public int IdDetale { get; set; }
        public int IdMaestro { get; set; }
        public int IdProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Impuesto { get; set; }
        public decimal Total { get; set; }
    
        public virtual tMaestro tMaestro { get; set; }
        public virtual tProducto tProducto { get; set; }
    }
}
